import axios from "axios";
import Head from "next/head";
import React, { Fragment, useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import Footer from "../../components/Footer/Footer";
import Profile from "../../components/Profile/index";
import NavbarDetail from "../../components/Navbar/NavbarDetail";
import { useRouter } from "next/router";

export async function getServerSideProps(context) {
  const id = context.params.id;
  console.log(id);
  const response = await axios.get(
    `${process.env.NEXT_APP_API_URL}/worker/${id}`
  );
  return {
    props: { detail: response?.data?.data?.worker[0] },
  };
}

export default function ProfileByID({ detail }) {
  const [portfolio, setPortfolio] = useState([]);
  const [experience, setExperience] = useState([]);
  const Router = useRouter();
  const id = Router.query.id;
  console.log(id);
  console.log(portfolio);

  const fetchPortfolio = async () => {
    const result = await axios.get(
      `${process.env.NEXT_APP_API_URL}/portfolio/${id}`
    );
    setPortfolio(result.data.data);
  };

  const fetchExperience = async () => {
    const result = await axios.get(
      `${process.env.NEXT_APP_API_URL}/experience/${id}`
    );
    setExperience(result.data.data);
  };

  useEffect(() => {
    fetchPortfolio();
    fetchExperience();
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Peworld - Profil Saya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-logo.ico" />
      </Head>
      <div className={`${styles.bg_profile} d-none d-sm-block d-md-block`}>
        <NavbarDetail />
        <div className={`${styles.bg}`}></div>
        <div></div>
        <Profile
          data={detail}
          skill={detail.skill}
          portfolio={portfolio}
          experience={experience}
        />
      </div>
      <Footer />
    </Fragment>
  );
}
