import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Swal from "sweetalert2";
import { useState } from "react";
import { useRouter } from "next/router";
import Logo from "../../assets/image/Icon.svg";
import styles from "../../styles/Login.module.css";

const RegistrasiRecruiter = () => {
  const router = useRouter();
  const [insertFormData, setInsertFormData] = useState({
    fullname: "",
    email: "",
    phonenumber: "",
    password: "",
  });

  const handleChange = (e) => {
    e.preventDefault();
    setInsertFormData({
      ...insertFormData,
      [e.target.name]: e.target.value,
    });
    console.log(insertFormData);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const result = await axios.post(
      `${process.env.NEXT_APP_API_URL}/authWorker/register`,
      insertFormData
    );
    console.log(result);
    Swal.fire({
      title: "Selamat!",
      text: "Silahkan login",
      icon: "success",
    });
    router.push("../login/worker");

    Swal.fire({
      title: "Upss!",
      text: error,
      icon: "error",
    });
  };

  return (
    <>
      <Head>
        <title>Peworld - Daftar Pelamar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-logo.ico" />
      </Head>
      <div className={`${styles.body}`}>
        <div className="container-fluid py-3 ">
          <div className="d-flex align-items-center justify-content-center  ">
            <div
              className={` d-none d-lg-flex ${styles.backdroplogin} ${styles.column} justify-content-center`}
            >
              <div className="mt-4 me-3">
                <Image
                  className={styles.logo}
                  src={Logo}
                  height={30}
                  alt="Logo"
                />
              </div>
              <div className="d-flex align-items-center">
                <h1 className="text-white mx-5 w-75">
                  Temukan developer berbakat & terbaik di berbagai bidang
                  keahlian
                </h1>
              </div>
            </div>
            <div className="container-fluid ">
              <div
                className={`${styles.column} d-flex align-items-center justify-content-center mt-5 pt-5`}
              >
                <form
                  // onSubmit={handleSubmit}
                  className={`d-flex flex-column ${styles.login} justify-content-center align-self-center`}
                >
                  <h1 className="text-center title-text">
                    <b>Halo, Peweople</b>
                  </h1>
                  <p className="subtitle-text text-center fs-5 my-4">
                    Buat akun Peworld milikmu sekarang!
                  </p>
                  <label
                    className={`align-self-start ${styles.inputLabelText} fw-bold`}
                    htmlFor="fullname"
                  >
                    Nama Lengkap
                  </label>
                  <input
                    type="text"
                    name="fullname"
                    className={`${styles.login} form-control my-2 mb-4`}
                    placeholder="Masukkan nama lengkap anda"
                    onChange={handleChange}
                  />
                  <label
                    className={`align-self-start ${styles.inputLabelText} fw-bold`}
                    htmlFor="email"
                  >
                    E-mail
                  </label>
                  <input
                    type="email"
                    name="email"
                    className={`${styles.login} form-control my-2 mb-4`}
                    placeholder="Masukkan e-mail anda"
                    onChange={handleChange}
                  />
                  <label
                    className={`align-self-start ${styles.inputLabelText} fw-bold`}
                    htmlFor="phonenumber"
                  >
                    No. HP
                  </label>
                  <input
                    type="number"
                    name="phonenumber"
                    className={`${styles.login} form-control my-2 mb-4`}
                    placeholder="Masukkan no. HP anda"
                    onChange={handleChange}
                  />
                  <label
                    className={`align-self-start ${styles.inputLabelText} fw-bold`}
                    htmlFor="password"
                  >
                    Kata sandi
                  </label>
                  <input
                    type="password"
                    name="password"
                    className={`${styles.login} form-control my-2 mb-4`}
                    placeholder="Masukkan kata sandi anda"
                    onChange={handleChange}
                  />
                  {/* <label
                    className={`align-self-start ${styles.inputLabelText} fw-bold`}
                    htmlFor="password"
                  >
                    Konfirmasi kata sandi
                  </label>
                  <input
                    type="password"
                    name="repassword"
                    className={`${styles.login} form-control my-2 mb-4`}
                    placeholder="Konfirmasi kata sandi anda"
                    onChange={handleChange}
                  /> */}

                  <label className="align-self-end fw-bold text-secondary mt-3 mb-3">
                    <Link href="../register/recruiter">
                      <span>Ingin merekrut pegawai?</span>
                    </Link>
                    <br />
                  </label>

                  {/* <Link href="/login"> */}
                  <button
                    type="submit"
                    className={`btn btn-warning ${styles.submit} text-white fs-5 w-100`}
                    onClick={handleSubmit}
                  >
                    Daftar
                  </button>
                  {/* </Link> */}

                  <br />
                  <label className="align-self-center fw-bold text-secondary">
                    Sudah punya akun?
                    <Link href="../login/worker">
                      <span className="text-warning ms-1">Masuk disini</span>
                    </Link>
                  </label>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default RegistrasiRecruiter;
