import Head from "next/head";
import Cookies from "js-cookie";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import Banner from "../components/Header/Banner";
import Footer from "../components/Footer/Footer";
import { Fragment, useEffect, useState } from "react";
import Navbar from "../components/Navbar/NavbarAfterLogin";
import { loadBanner } from "./api";

export async function getStaticProps() {
  const detail = await loadBanner();
  return { props: { detail } };
}

export default function Home({ detail }) {
  const token = Cookies.get("token");
  const router = useRouter();

  useEffect(() => {
    if (!token) {
      router.push("/login/worker");
    }
  }, []);

  return (
    <Fragment>
      <div className={`${styles.container}`}>
        <Head>
          <title>Peworld - Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icon-logo.ico" />
        </Head>
        <Navbar />
        <Banner data={detail} />
      </div>
      <Footer />
    </Fragment>
  );
}
