import axios from "axios";
import Head from "next/head";
import Cookies from "js-cookie";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer/Footer";
import Profile from "../components/Profile/profile";
import NavbarDetail from "../components/Navbar/NavbarDetail";
import React, { Fragment, useEffect, useState } from "react";

export default function ProfileDetail() {
  const [detail, setDetail] = useState([]);
  const [portfolio, setPortfolio] = useState([]);
  const [experience, setExperience] = useState([]);

  const id = Cookies.get("id");
  const token = Cookies.get("token");

  const fetchProfile = async () => {
    const result = await axios.get(
      `${process.env.NEXT_APP_API_URL}/authWorker/profile`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );
    console.log(result);
    console.log(id);
    setDetail(result.data.data[0]);
  };

  const fetchPortfolio = async () => {
    const result = await axios.get(
      `${process.env.NEXT_APP_API_URL}/portfolio/${id}`
    );
    console.log(result);
    setPortfolio(result.data.data);
  };

  const fetchExperience = async () => {
    const result = await axios.get(
      `${process.env.NEXT_APP_API_URL}/experience/${id}`
    );
    console.log(result);
    setExperience(result.data.data);
  };

  useEffect(() => {
    fetchProfile();
    fetchPortfolio();
    fetchExperience();
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Peworld - Detil Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-logo.ico" />
      </Head>
      <div className={`${styles.bg_profile}`}>
        <NavbarDetail />
        <div className={`${styles.bg}`}></div>
        <Profile
          data={detail}
          skill={detail.skill}
          portfolio={portfolio}
          experience={experience}
        />
      </div>
      <Footer />
    </Fragment>
  );
}
